apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: rag2-rm-annotate-aug14-llama-1-repository
spec:
  url: https://github.com/redhat-appstudio-mjf/rag2-rm-annotate-aug14-llama-1